version: "3"
services:
    app:
        build: docker/app
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
            MYSQL_PORT: ${MYSQL_PORT}
        volumes:
            - ./docker/app/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
            - ./docker/app/conf.d/cms.ini:/usr/local/etc/php/conf.d/drupal.ini:ro
            - .:/var/www/formation:delegated
            - ~/.composer:/home/docker/.composer:delegated

    mysql:
        image: mysql:5.6
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - mysql-data:/var/lib/mysql:delegated
            - ./dump:/docker-entrypoint-initdb.d:ro

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/log:/var/log/nginx:delegated
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/formation:ro

    mailcatcher:
        image: zolweb/docker-mailcatcher:latest
        ports:
            - "1080:1080"
volumes:
    mysql-data: ~
